source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
//
target 'shanglvjia' do
        pod 'SVProgressHUD'
    	pod 'SnapKit', '~> 3.0.2'
        pod 'Masonry'
    	pod 'MJExtension'
        pod 'MJRefresh'
    	pod 'FMDB'
        pod 'UMengAnalytics-NO-IDFA'#//无IDFA版SDK（请根据需要选择其中一个）
        pod 'SDWebImage', '~> 4.0.0'
        pod 'Alamofire', '~> 4.0'
    	pod 'SwiftyJSON', '~> 3.1.4'
    	pod 'JPush'
        pod 'IQKeyboardManagerSwift','5.0.0' #'4.0.8'
        pod 'AMap3DMap-NO-IDFA'
        pod 'AMapLocation-NO-IDFA'
        pod 'AMapSearch-NO-IDFA'
        pod 'WechatOpenSDK'
        pod 'RxSwift',’3.6.1’
        pod 'RxCocoa'
        pod 'Moya/RxSwift’
        pod 'Moya-SwiftyJSONMapper/RxSwift', '~> 2.2.0’
        pod 'SwiftDate', '~> 4.3.0’
        pod 'RxOptional'
        pod 'RxDataSources'
        pod 'KissXML'
        #pod 'KissXML/SwiftNSXML'
        pod 'UMengUShare/Social/ReducedWeChat'
        pod 'UMengUShare/Social/ReducedQQ'
        pod 'HandyJSON', '~> 4.2.0'
        pod 'ReachabilitySwift'
        
end

target 'shanglvjiaTests' do
     pod 'SVProgressHUD'
    pod 'SnapKit', '~> 3.0.2'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'FMDB'
    pod 'AMapLocation-NO-IDFA'
    pod 'AMapSearch-NO-IDFA'
    pod 'IQKeyboardManagerSwift', '5.0.0' #'4.0.8'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'JPush'
    pod 'RxSwift',’3.6.1’
    pod 'RxCocoa'
    pod 'Moya/RxSwift'
    pod 'Moya-SwiftyJSONMapper/RxSwift’,’~> 2.2.0’
    pod 'SwiftDate', '~> 4.3.0’
    pod 'RxOptional'
    pod 'RxDataSources'
    pod 'HandyJSON', '~> 4.2.0'
    pod 'ReachabilitySwift'
    
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end
end
